# Swing Vision Transformation

#### Converting SwingVision data into our format

#### Trying to find other swingvision data:

- https://bubbletao.com/2019/03/31/tennis-score-tracking-and-exported-data-analysis-with-apple-watch-using-swing-app/  (no data, but walks through common errors and fixes in data)

# Comparing website manually tagged data

### Load in Data

In [ ]:
import pandas as pd
import numpy as np
import os 
import re

# Option to display max rows/columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [ ]:
your_file_name = ''
clean_df = pd.read_csv(your_file_name

In [ ]:
clean_df.shape

In [ ]:
clean_df.head(20)

# Notebook Start

### Load in data

In [1]:
import pandas as pd
import numpy as np
import os 
import re

# Option to display max rows/columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [2]:
# Input file name here
your_file_name = 'Rudy_Youcef_FSU_sv.xlsx'
swing_data = pd.read_excel(your_file_name, sheet_name='Shots')
swing_data.shape

(677, 25)

In [3]:
swing_data.head()

,Player,Shot,Type,Stroke,Spin,Speed (MPH),Point,Game,Set,Bounce Depth,Bounce Zone,Bounce Side,Bounce (x),Bounce (y),Hit Depth,Hit Zone,Hit Side,Hit (x),Hit (y),Hit (z),Direction,Result,Favorited,Start Time,Video Time
0,Rudy Quan,1,first_serve,Serve,Flat,78.818588,1,1,1,short,deuce,near,0.375670,6.704057,out,deuce,far,-1.587323,22.818127,2.682724,down the T,In,False,21:13:17,12.080000
1,Youcef Rihane,2,first_return,Backhand,Topspin,51.792099,1,1,1,deep,deuce,far,-0.948239,19.035049,out,deuce,near,1.339200,-1.593285,0.891651,inside out,In,False,21:13:18,13.040000
2,Rudy Quan,3,serve_plus_one,Forehand,Topspin,58.796837,1,1,1,deep,ad,near,-1.727404,0.906123,deep,deuce,far,-1.565159,24.191404,1.197903,down the line,In,False,21:13:19,14.300000
3,Youcef Rihane,4,return_plus_one,Backhand,Topspin,49.338074,1,1,1,out,ad,far,2.808425,24.438177,out,ad,near,-1.930130,-1.595187,0.957120,cross court,Out,False,21:13:20,15.500000
4,Rudy Quan,5,in_play,Backhand,Flat,56.885868,1,1,1,deep,ad,near,-2.039777,4.713785,deep,ad,far,2.808425,24.145630,0.636929,cross court,In,False,21:13:21,16.959999

### Clean swing vision data

In [4]:
swing_data.query('Stroke == "Feed"').head()

,Player,Shot,Type,Stroke,Spin,Speed (MPH),Point,Game,Set,Bounce Depth,Bounce Zone,Bounce Side,Bounce (x),Bounce (y),Hit Depth,Hit Zone,Hit Side,Hit (x),Hit (y),Hit (z),Direction,Result,Favorited,Start Time,Video Time
30,Youcef Rihane,0,none,Feed,Flat,19.052607,5,1,1,short,deuce,far,-0.485830,18.041225,short,deuce,near,1.002303,7.083730,1.791148,---,In,False,21:15:11,126.760002
61,Rudy Quan,0,none,Feed,Flat,20.784662,10,2,1,short,deuce,far,-1.249201,16.799627,deep,deuce,near,1.514472,0.542222,0.617660,---,In,False,21:18:24,319.549988
74,Youcef Rihane,0,none,Feed,Flat,23.382744,12,3,1,short,ad,near,-0.473872,6.239765,deep,deuce,far,-3.208965,20.970543,2.106119,---,In,False,21:19:30,385.119995
75,Youcef Rihane,1,none,Feed,Flat,18.186579,12,3,1,deep,ad,near,-2.165251,3.997676,deep,deuce,far,-3.153087,21.960804,2.471642,---,In,False,21:19:38,393.329987
80,Youcef Rihane,0,none,Feed,Flat,20.784662,13,3,1,deep,ad,near,-2.438261,4.502622,short,deuce,far,-3.327099,16.743202,1.614205,---,In,False,21:20:19,434.989990

In [5]:
swing_data.query('Shot == 0').head()

,Player,Shot,Type,Stroke,Spin,Speed (MPH),Point,Game,Set,Bounce Depth,Bounce Zone,Bounce Side,Bounce (x),Bounce (y),Hit Depth,Hit Zone,Hit Side,Hit (x),Hit (y),Hit (z),Direction,Result,Favorited,Start Time,Video Time
30,Youcef Rihane,0,none,Feed,Flat,19.052607,5,1,1,short,deuce,far,-0.485830,18.041225,short,deuce,near,1.002303,7.083730,1.791148,---,In,False,21:15:11,126.760002
61,Rudy Quan,0,none,Feed,Flat,20.784662,10,2,1,short,deuce,far,-1.249201,16.799627,deep,deuce,near,1.514472,0.542222,0.617660,---,In,False,21:18:24,319.549988
74,Youcef Rihane,0,none,Feed,Flat,23.382744,12,3,1,short,ad,near,-0.473872,6.239765,deep,deuce,far,-3.208965,20.970543,2.106119,---,In,False,21:19:30,385.119995
80,Youcef Rihane,0,none,Feed,Flat,20.784662,13,3,1,deep,ad,near,-2.438261,4.502622,short,deuce,far,-3.327099,16.743202,1.614205,---,In,False,21:20:19,434.989990
87,Youcef Rihane,0,none,Feed,Flat,22.516716,14,3,1,short,ad,near,-1.952927,7.803154,deep,deuce,far,-2.221235,21.249830,2.106010,---,In,False,21:20:48,463.369995

In [6]:
swing_data.query('Type == "none"').head()

,Player,Shot,Type,Stroke,Spin,Speed (MPH),Point,Game,Set,Bounce Depth,Bounce Zone,Bounce Side,Bounce (x),Bounce (y),Hit Depth,Hit Zone,Hit Side,Hit (x),Hit (y),Hit (z),Direction,Result,Favorited,Start Time,Video Time
30,Youcef Rihane,0,none,Feed,Flat,19.052607,5,1,1,short,deuce,far,-0.485830,18.041225,short,deuce,near,1.002303,7.083730,1.791148,---,In,False,21:15:11,126.760002
61,Rudy Quan,0,none,Feed,Flat,20.784662,10,2,1,short,deuce,far,-1.249201,16.799627,deep,deuce,near,1.514472,0.542222,0.617660,---,In,False,21:18:24,319.549988
74,Youcef Rihane,0,none,Feed,Flat,23.382744,12,3,1,short,ad,near,-0.473872,6.239765,deep,deuce,far,-3.208965,20.970543,2.106119,---,In,False,21:19:30,385.119995
75,Youcef Rihane,1,none,Feed,Flat,18.186579,12,3,1,deep,ad,near,-2.165251,3.997676,deep,deuce,far,-3.153087,21.960804,2.471642,---,In,False,21:19:38,393.329987
77,Youcef Rihane,3,none,Backhand,Flat,42.652466,12,3,1,short,deuce,near,2.457301,9.337544,out,deuce,far,-2.024198,26.844564,1.261113,inside out,In,False,21:20:00,415.619995

#### Remove all the rows where it is a feed

In [7]:
rows_to_drop = swing_data.query('Type == "none"').index
swing_data = swing_data.drop(rows_to_drop)
# Important to reindex to avoid missing indicies
swing_data = swing_data.reset_index(drop=True)
swing_data.shape

(615, 25)

In [8]:
swing_data.head()

,Player,Shot,Type,Stroke,Spin,Speed (MPH),Point,Game,Set,Bounce Depth,Bounce Zone,Bounce Side,Bounce (x),Bounce (y),Hit Depth,Hit Zone,Hit Side,Hit (x),Hit (y),Hit (z),Direction,Result,Favorited,Start Time,Video Time
0,Rudy Quan,1,first_serve,Serve,Flat,78.818588,1,1,1,short,deuce,near,0.375670,6.704057,out,deuce,far,-1.587323,22.818127,2.682724,down the T,In,False,21:13:17,12.080000
1,Youcef Rihane,2,first_return,Backhand,Topspin,51.792099,1,1,1,deep,deuce,far,-0.948239,19.035049,out,deuce,near,1.339200,-1.593285,0.891651,inside out,In,False,21:13:18,13.040000
2,Rudy Quan,3,serve_plus_one,Forehand,Topspin,58.796837,1,1,1,deep,ad,near,-1.727404,0.906123,deep,deuce,far,-1.565159,24.191404,1.197903,down the line,In,False,21:13:19,14.300000
3,Youcef Rihane,4,return_plus_one,Backhand,Topspin,49.338074,1,1,1,out,ad,far,2.808425,24.438177,out,ad,near,-1.930130,-1.595187,0.957120,cross court,Out,False,21:13:20,15.500000
4,Rudy Quan,5,in_play,Backhand,Flat,56.885868,1,1,1,deep,ad,near,-2.039777,4.713785,deep,ad,far,2.808425,24.145630,0.636929,cross court,In,False,21:13:21,16.959999

### Load in Points data

In [9]:
swing_data_points = pd.read_excel(your_file_name, sheet_name='Points')
swing_data_points.shape

(97, 15)

In [10]:
def create_point(server, player1score, player2score):
    if server == "host":
        return str(player1score) + "-" + str(player2score)
    else:
        return str(player2score) + "-" + str(player1score)
    
swing_data_points['pointScore'] = swing_data_points.apply(lambda x: create_point(x['Match Server'], x['Host Game Score'], x['Guest Game Score']), axis=1)

In [11]:
swing_data_points = swing_data_points.rename(columns={'Break Point' : 'isBreakPoint'})
swing_data_points['isBreakPoint'] = swing_data_points['isBreakPoint'].replace(False, '')
swing_data_points['isBreakPoint'] = swing_data_points['isBreakPoint'].replace(True, 1)

In [12]:
swing_data_points = swing_data_points[['Point', 'pointScore', 'isBreakPoint']]
swing_data_points

    Point pointScore isBreakPoint
0       1        0-0
1       2       0-15
2       3       0-30
3       4       0-40            1
4       5      15-40            1
5       6        0-0
6       7       15-0
7       8      15-15
8       9      15-30
9      10      15-40            1
10     11      30-40            1
11     12        0-0
12     13       15-0
13     14       30-0
14     15       40-0
15     16        0-0
16     17       15-0
17     18       30-0
18     19      30-15
19     20      40-15
20     21        0-0
21     22       0-15
22     23      15-15
23     24      30-15
24     25      40-15
25     26        0-0
26     27       15-0
27     28       30-0
28     29      30-15
29     30      40-15
30     31        0-0
31     32       15-0
32     33      15-15
33     34      15-30
34     35      30-30
35     36      40-30
36     37        0-0
37     38       0-15
38     39      15-15
39     40      30-15
40     41      40-15
41     42        0-0
42     43       15-0
43     44      15-15
44     45      30-15
45     46      40-15
46     47        0-0
47     48       0-15
48     49      15-15
49     50      15-30
50     51      15-40            1
51     52      30-40            1
52     53        0-0
53     54       15-0
54     55      15-15
55     56      15-30
56     57      15-40            1
57     58      30-40            1
58     59        0-0
59     60       0-15
60     61       0-30
61     62       0-40            1
62     63      15-40            1
63     64      30-40            1
64     65        0-0
65     66       15-0
66     67      15-15
67     68      15-30
68     69      30-30
69     70      40-30
70     71        0-0
71     72       15-0
72     73      15-15
73     74      15-30
74     75      30-30
75     76      30-40            1
76     77      40-40            1
77     78        0-0
78     79       0-15
79     80      15-15
80     81      30-15
81     82      40-15
82     83      40-30
83     84        0-0
84     85       15-0
85     86       30-0
86     87       40-0
87     88      40-15
88     89        0-0
89     90       15-0
90     91       30-0
91     92       40-0
92     93        0-0
93     94       15-0
94     95      15-15
95     96      15-30
96     97      15-40            1

In [13]:
swing_data = pd.merge(swing_data, swing_data_points, on='Point')

### Load in Games data

In [14]:
swing_data_games = pd.read_excel(your_file_name, sheet_name='Games')
swing_data_games.shape

(18, 9)

In [15]:
swing_data_games.head()

,Game,Set,Server,Host Set Score,Guest Set Score,Game Winner,Start Time,Video Time,Duration
0,1,1,host,0,0,guest,21:13:19,14.080000,131.729996
1,2,1,guest,0,1,host,21:15:30,145.800003,233.419998
2,3,1,host,1,1,host,21:19:24,379.220001,139.190002
3,4,1,guest,2,1,guest,21:21:43,518.409973,190.589996
4,5,1,host,2,2,host,21:24:54,709.000000,199.179993

In [16]:
def create_game(player1game, player2game):
        return str(player1game) + "-" + str(player2game)
    
swing_data_games['gameScore'] = swing_data_games.apply(lambda x: create_game(x['Host Set Score'], x['Guest Set Score']), axis=1)

In [17]:
swing_data_games.head()

,Game,Set,Server,Host Set Score,Guest Set Score,Game Winner,Start Time,Video Time,Duration,gameScore
0,1,1,host,0,0,guest,21:13:19,14.080000,131.729996,0-0
1,2,1,guest,0,1,host,21:15:30,145.800003,233.419998,0-1
2,3,1,host,1,1,host,21:19:24,379.220001,139.190002,1-1
3,4,1,guest,2,1,guest,21:21:43,518.409973,190.589996,2-1
4,5,1,host,2,2,host,21:24:54,709.000000,199.179993,2-2

In [18]:
swing_data_games = swing_data_games[['Game', 'gameScore']]

In [19]:
swing_data = pd.merge(swing_data, swing_data_games, on="Game")

In [20]:
swing_data

,Player,Shot,Type,Stroke,Spin,Speed (MPH),Point,Game,Set,Bounce Depth,Bounce Zone,Bounce Side,Bounce (x),Bounce (y),Hit Depth,Hit Zone,Hit Side,Hit (x),Hit (y),Hit (z),Direction,Result,Favorited,Start Time,Video Time,pointScore,isBreakPoint,gameScore
0,Rudy Quan,1,first_serve,Serve,Flat,78.818588,1,1,1,short,deuce,near,0.375670,6.704057,out,deuce,far,-1.587323,22.818127,2.682724,down the T,In,False,21:13:17,12.080000,0-0,,0-0
1,Youcef Rihane,2,first_return,Backhand,Topspin,51.792099,1,1,1,deep,deuce,far,-0.948239,19.035049,out,deuce,near,1.339200,-1.593285,0.891651,inside out,In,False,21:13:18,13.040000,0-0,,0-0
2,Rudy Quan,3,serve_plus_one,Forehand,Topspin,58.796837,1,1,1,deep,ad,near,-1.727404,0.906123,deep,deuce,far,-1.565159,24.191404,1.197903,down the line,In,False,21:13:19,14.300000,0-0,,0-0
3,Youcef Rihane,4,return_plus_one,Backhand,Topspin,49.338074,1,1,1,out,ad,far,2.808425,24.438177,out,ad,near,-1.930130,-1.595187,0.957120,cross court,Out,False,21:13:20,15.500000,0-0,,0-0
4,Rudy Quan,5,in_play,Backhand,Flat,56.885868,1,1,1,deep,ad,near,-2.039777,4.713785,deep,ad,far,2.808425,24.145630,0.636929,cross court,In,False,21:13:21,16.959999,0-0,,0-0
5,Youcef Rihane,6,in_play,Backhand,Flat,68.713676,1,1,1,deep,ad,far,2.133324,20.077675,out,ad,near,-3.015850,-1.274592,0.642954,cross court,In,False,21:13:23,18.360001,0-0,,0-0
6,Rudy Quan,7,in_play,Backhand,Flat,63.736755,1,1,1,deep,ad,near,-3.952259,2.891359,out,ad,far,3.255260,25.223696,0.907917,cross court,In,False,21:13:24,19.719999,0-0,,0-0
7,Youcef Rihane,8,in_play,Backhand,Flat,60.174286,1,1,1,deep,ad,far,1.379859,18.931719,out,ad_alley,near,-4.936730,-1.900042,1.078391,down the line,In,False,21:13:26,21.059999,0-0,,0-0
8,Rudy Quan,9,in_play,Backhand,Flat,75.110580,1,1,1,deep,deuce,near,0.745801,2.758727,deep,ad,far,2.938291,24.862993,1.009418,down the line,In,False,21:13:27,22.530001,0-0,,0-0
9,Youcef Rihane,10,in_play,Forehand,Topspin,48.032726,1,1,1,short,deuce,far,-0.469121,12.562120,out,deuce,near,0.271786,-1.095737,1.005636,cross court,In,False,21:13:28,23.590000,0-0,,0-0
10,Rudy Quan,11,in_play,Forehand,Flat,66.510574,1,1,1,deep,deuce,near,1.930779,2.086064,out,deuce,far,-2.286640,25.216394,1.030771,cross court,In,False,21:13:30,25.120001,0-0,,0-0
11,Youcef Rihane,12,in_play,Forehand,Topspin,68.919586,1,1,1,deep,deuce,far,-1.520248,18.325665,deep,deuce,near,1.897198,-0.477758,1.172586,cross court,In,False,21:13:31,26.290001,0-0,,0-0
12,Rudy Quan,13,in_play,Forehand,Topspin,57.461922,1,1,1,deep,deuce,near,0.882558,2.423987,deep,deuce,far,-2.921525,24.424807,1.041313,cross court,In,False,21:13:32,27.469999,0-0,,0-0
13,Youcef Rihane,14,in_play,Forehand,Topspin,72.094711,1,1,1,deep,deuce,far,-2.705063,19.162331,out,deuce,near,0.779029,-0.527214,1.026741,cross court,In,False,21:13:33,28.690001,0-0,,0-0
14,Rudy Quan,15,in_play,Forehand,Flat,31.601217,1,1,1,short,deuce,far,-3.057388,12.394547,out,deuce_alley,far,-4.300917,26.060057,0.802144,down the line,Net,False,21:13:34,29.790001,0-0,,0-0
15,Rudy Quan,1,first_serve,Serve,Flat,73.550629,2,1,1,short,ad,near,-2.381464,5.856773,out,ad,far,0.288185,23.267712,2.621755,out wide,In,False,21:14:01,56.040001,0-15,,0-0
16,Youcef Rihane,2,first_return,Backhand,Flat,54.201843,2,1,1,deep,deuce,far,-1.009888,18.755064,out,ad_alley,near,-4.333957,-1.993100,0.904940,down the line,In,False,21:14:02,57.150002,0-15,,0-0
17,Rudy Quan,3,serve_plus_one,Forehand,Topspin,69.508339,2,1,1,deep,deuce,near,3.088044,3.279717,out,deuce,far,-0.852586,25.276489,0.971329,cross court,In,False,21:14:03,58.619999,0-15,,0-0
18,Youcef Rihane,4,return_plus_one,Forehand,Flat,51.827076,2,1,1,deep,deuce,far,-3.544693,21.911123,out,deuce,near,3.842897,-1.943556,0.838094,cross court,In,False,21:14:04,59.680000,0-15,,0-0
19,Rudy Quan,5,in_play,Forehand,Topspin,44.094707,2,1,1,short,ad,near,-2.489522,5.824504,out,deuce,far,-4.006272,25.997301,1.245638,down the line,In,False,21:14:06,61.080002,0-15,,0-0
20,Youcef Rihane,6,in_play,Backhand,Topspin,67.187683,2,1,1,deep,deuce,far,-3.824315,19.455873,deep,ad,near,-2.133938,0.959097,0.917877,down the line,In,False,21:14:07,62.740002,0-15,,0-0
21,Rudy Quan,1,first_serve,Serve,Slice,77.925125,3,1,1,short,deuce,near,4.035830,5.927059,deep,deuce,far,-1.206906,24.769407,2.717144,out wide,In,False,21:14:29,84.330002,0-30,,0-0
22,Youcef Rihane,2,first_return,Forehand,Topspin,59.380085,3,1,1,deep,deuce,far,-0.412435,23.124138,out,deuce_alley,near,5.093851,-0.608967,0.807649,down the line,In,False,21:14:30,85.440002,0-30,,0-0
23,Rudy Quan,3,serve_plus_one,Forehand,Topspin,35.202026,3,1,1,short,deuce,near,2.139843,6.368892,out,deuce,far,-1.059200,25.314693,1.022047,cross court,In,False,21:14:31,86.570000,0-30,,0-0
24,Youcef Rihane,4,return_plus_one,Forehand,Topspin,64.126556,3,1,1,deep,ad,far,3.601790,21.484306,deep,deuce,near,2.342912,1.920074,1.368985,down the line,In,False,21:14:33,88.570000,0-30,,0-0
25,Rudy Quan,5,in_play,Backhand,Topspin,52.732723,3,1,1,short,ad,far,1.202777,17.534847,out,ad,far,3.664908,25.644354,1.064472,cross court,Net,False,21:14:34,89.760002,0-30,,0-0
26,Rudy Quan,1,first_serve,Serve,Flat,74.387207,4,1,1,short,ad,near,-2.556470,7.416546,short,ad,far,0.196180,23.624725,2.785779,out wide,In,False,21:14:58,113.970001,0-40,1,0-0
27,Youcef Rihane,2,first_return,Backhand,Topspin,61.212284,4,1,1,deep,ad,far,1.382944,19.933245,out,ad_alley,near,-4.185227,-1.058298,0.991407,down the line,In,False,21:15:00,115.050003,0-40,1,0-0
28,Rudy Quan,3,serve_plus_one,Backhand,Flat,54.567707,4,1,1,short,ad,near,-3.217104,6.003235,out,ad,far,2.334615,25.084330,0.963492,cross court,In,False,21:15:01,116.199997,0-40,1,0-0
29,Youcef Rihane,4,return_plus_one,Backhand,Flat,61.946915,4,1,1,short,ad,near,-1.749751,10.946201,deep,ad_alley,near,-4.537301,-0.500219,0.511123,down the line,Net,False,21:15:02,117.830002,0-40,1,0-0
30,Rudy Quan,1,first_serve,Serve,Flat,74.829308,5,1,1,short,deuce,near,0.652064,6.409086,deep,deuce,far,-1.610155,23.954283,2.745763,down the T,In,False,21:15:23,138.889999,15-40,1,0-0
31,Youcef Rihane,2,first_return,Backhand,Topspin,56.984936,5,1,1,deep,deuce,far,-0.551843,19.249617,out,deuce,near,1.803398,-1.954390,0.842386,inside out,In,False,21:15:25,140.029999,15-40,1,0-0
32,Rudy Quan,3,serve_plus_one,Forehand,Topspin,71.010056,5,1,1,deep,ad,near,-2.561484,3.044526,out,deuce,far,-1.549707,25.221220,0.955758,down the line,In,False,21:15:26,141.389999,15-40,1,0-0
33,Youcef Rihane,4,return_plus_one,Backhand,Flat,48.807854,5,1,1,deep,ad,far,2.392957,23.527733,out,ad,near,-2.700570,-2.465371,0.605451,cross court,In,False,21:15:27,142.500000,15-40,1,0-0
34,Youcef Rihane,1,first_serve,Serve,Flat,121.590271,6,2,1,deep,deuce,near,3.412694,5.223339,deep,deuce,far,-0.950916,24.719778,2.500092,out wide,Out,False,21:16:21,196.100006,0-0,,0-1
35,Rudy Quan,2,first_return,Forehand,Flat,58.276226,6,2,1,deep,ad,far,0.231998,20.794306,out,deuce_alley,near,4.411157,-1.531472,1.119726,down the line,In,False,21:16:21,196.869995,0-0,,0-1
36,Youcef Rihane,3,serve_plus_one,Forehand,Topspin,58.627354,6,2,1,short,deuce,near,1.874955,6.067075,out,deuce,far,-0.570850,25.769667,1.170846,cross court,In,False,21:16:23,198.130005,0-0,,0-1
37,Rudy Quan,4,return_plus_one,Forehand,Topspin,67.829521,6,2,1,deep,ad_alley,far,4.648556,22.221548,deep,deuce,near,2.858268,0.580277,1.060871,down the line,Out,False,21:16:24,199.500000,0-0,,0-1
38,Youcef Rihane,1,first_serve,Serve,Flat,81.970482,7,2,1,short,ad,near,-2.375968,6.910823,deep,ad,far,0.908278,24.764486,2.652869,out wide,In,False,21:16:40,215.729996,15-0,,0-1
39,Rudy Quan,2,first_return,Backhand,Topspin,53.009319,7,2,1,deep,deuce,far,-1.348009,18.540995,out,ad_alley,near,-4.604066,-1.698448,0.715455,down the line,In,False,21:16:41,216.830002,15-0,,0-1
40,Youcef Rihane,3,serve_plus_one,Forehand,Topspin,71.988197,7,2,1,deep,deuce,near,2.979218,2.902682,out,deuce,far,-0.968803,25.925825,0.902372,cross court,In,False,21:16:43,218.300003,15-0,,0-1
41,Rudy Quan,4,return_plus_one,Forehand,Topspin,55.163200,7,2,1,deep,deuce,far,-1.105032,22.913887,out,deuce,near,3.693256,-1.419443,0.795678,cross court,In,False,21:16:44,219.509995,15-0,,0-1
42,Youcef Rihane,5,in_play,Forehand,Topspin,47.466213,7,2,1,deep,ad,near,-2.777045,5.192045,out,deuce,far,-1.947315,26.281105,0.987656,down the line,In,False,21:16:45,220.830002,15-0,,0-1
43,Rudy Quan,6,in_play,Backhand,Topspin,66.747658,7,2,1,deep,ad,far,2.706649,19.221039,deep,ad,near,-3.176717,0.171342,1.059574,cross court,In,False,21:16:47,222.399994,15-0,,0-1
44,Youcef Rihane,7,in_play,Backhand,Flat,52.297890,7,2,1,short,ad,far,0.868372,12.349630,deep,ad,far,3.749040,24.720764,0.798362,cross court,Net,False,21:16:48,223.619995,15-0,,0-1
45,Youcef Rihane,1,first_serve,Serve,Flat,42.975437,8,2,1,short,deuce,near,0.718206,7.597571,deep,deuce,far,-1.014871,23.927023,2.575193,down the T,In,False,21:17:19,254.229996,15-15,,0-1
46,Rudy Quan,2,first_return,Backhand,Flat,48.894547,8,2,1,deep,deuce,far,-0.931851,18.875166,out,deuce,near,1.413325,-0.732939,0.884555,inside out,In,False,21:17:20,255.490005,15-15,,0-1
47,Youcef Rihane,3,serve_plus_one,Forehand,Flat,87.395851,8,2,1,deep,deuce,near,3.509119,4.007685,deep,deuce,far,-1.602948,24.136541,1.112495,cross court,In,False,21:17:22,257.040009,15-15,,0-1
48,Rudy Quan,4,return_plus_one,Forehand,Topspin,52.760063,8,2,1,deep,ad,far,0.065196,21.961863,out,deuce_alley,near,4.309384,-1.305329,0.784065,down the line,In,False,21:17:23,258.089996,15-15,,0-1
49,Youcef Rihane,5,in_play,Forehand,Topspin,62.848461,8,2,1,deep,ad,near,-2.548905,3.051773,out,deuce,far,-0.538388,25.199406,1.330265,down the line,In,False,21:17:24,259.440002,15-15,,0-1
50,Rudy Quan,6,in_play,Backhand,Slice,38.173969,8,2,1,deep,deuce,far,-0.517908,19.796545,out,ad,near,-3.123801,-2.314595,0.704499,down the line,In,False,21:17:25,260.790009,15-15,,0-1
51,Youcef Rihane,7,in_play,Forehand,Flat,53.279766,8,2,1,short,deuce,far,-1.552227,12.540694,deep,deuce,far,-0.202452,22.437880,1.294729,cross court,Net,False,21:17:28,263.040009,15-15,,0-1
52,Youcef Rihane,1,first_serve,Serve,Flat,53.982105,9,2,1,short,deuce,far,-1.449809,11.919669,deep,ad,far,0.587860,24.841330,2.626560,down the T,Net,False,21:17:54,289.220001,15-30,,0-1
53,Youcef Rihane,1,second_serve,Serve,Slice,64.673111,9,2,1,short,ad,near,-2.922318,7.919921,deep,ad,far,0.358135,23.310579,2.626416,out wide,In,False,21:18:07,302.589996,15-30,,0-1
54,Rudy Quan,2,second_return,Backhand,Flat,55.844570,9,2,1,deep,ad,far,1.197363,21.595804,deep,ad_alley,near,-5.155694,-0.380336,1.014004,down the line,In,False,21:18:08,303.600006,15-30,,0-1
55,Youcef Rihane,3,serve_plus_one,Forehand,Topspin,63.007000,9,2,1,deep,deuce,near,2.450933,3.020874,out,ad,far,1.650528,25.720747,1.116962,inside in,In,False,21:18:09,304.890015,15-30,,0-1
56,Rudy Quan,4,return_plus_one,Forehand,Topspin,57.666908,9,2,1,deep,deuce,far,-1.287905,19.137754,out,deuce,near,2.256483,-2.028357,0.985214,cross court,In,False,21:18:11,306.109985,15-30,,0-1
57,Youcef Rihane,5,in_play,Forehand,Topspin,61.989937,9,2,1,deep,ad,near,-3.432542,1.486513,out,deuce,far,-2.525463,25.601118,0.865489,down the line,In,False,21:18:12,307.470001,15-30,,0-1
58,Rudy Quan,6,in_play,Backhand,Topspin,50.350174,9,2,1,deep,ad,far,1.645349,21.250500,out,ad,near,-3.584215,-2.073938,0.985114,cross court,In,False,21:18:13,308.679993,15-30,,0-1
59,Youcef Rihane,7,in_play,Forehand,Topspin,64.319519,9,2,1,out,deuce,near,3.551332,-1.481627,out,ad,far,1.507085,25.340944,1.147004,inside in,Out,False,21:18:15,310.100006,15-30,,0-1
60,Youcef Rihane,1,first_serve,Serve,Flat,130.596954,10,2,1,short,deuce,near,1.437568,7.459099,deep,deuce,far,-0.492790,23.649343,2.871758,down the T,In,False,21:18:41,336.410004,15-40,1,0-1
61,Rudy Quan,2,first_return,Backhand,Flat,38.760319,10,2,1,short,deuce,near,0.845458,11.354012,out,deuce,near,2.033012,-0.927040,0.813399,inside out,Net,False,21:18:42,337.059998,15-40,1,0-1
62,Youcef Rihane,1,first_serve,Serve,Flat,99.551529,11,2,1,short,ad_alley,near,-4.313514,6.224525,deep,ad,far,0.718070,23.846155,2.726489,out wide,Out,False,21:19:01,356.970001,30-40,1,0-1
63,Youcef Rihane,1,second_serve,Serve,Slice,63.984833,11,2,1,short,ad,near,-2.317964,7.148214,deep,ad,far,0.825759,23.400476,2.471947,out wide,In,False,21:19:10,365.929993,30-40,1,0-1
64,Rudy Quan,2,second_return,Backhand,Flat,59.398296,11,2,1,deep,ad,far,1.795720,18.695372,deep,ad,near,-3.419441,0.928015,1.160089,cross court,In,False,21:19:12,367.010010,30-40,1,0-1
65,Youcef Rihane,3,serve_plus_one,Backhand,Topspin,60.821030,11,2,1,deep,ad,near,-3.280692,4.027934,deep,ad,far,3.212224,24.961016,1.080395,cross court,In,False,21:19:13,368.329987,30-40,1,0-1
66,Rudy Quan,4,return_plus_one,Backhand,Topspin,61.654285,11,2,1,deep,ad,far,2.760654,22.561460,out,ad_alley,near,-4.603194,-2.139278,0.831091,down the line,In,False,21:19:14,369.630005,30-40,1,0-1
67,Youcef Rihane,5,in_play,Backhand,Topspin,55.237373,11,2,1,deep,ad,near,-1.432269,4.881042,out,ad,far,3.185396,24.985079,0.807212,cross court,In,False,21:19:15,370.929993,30-40,1,0-1
68,Rudy Quan,6,in_play,Backhand,Flat,63.037075,11,2,1,deep,ad,far,3.933489,20.383938,out,ad,near,-2.714908,-0.970798,0.651204,cross court,In,False,21:19:17,372.380005,30-40,1,0-1
69,Youcef Rihane,7,in_play,Backhand,Flat,54.952297,11,2,1,short,center_line,near,0.024528,5.538774,out,ad_alley,far,4.610608,25.570784,0.997255,down the line,In,False,21:19:18,373.690002,30-40,1,0-1
70,Rudy Quan,8,in_play,Forehand,Topspin,56.323231,11,2,1,deep,deuce,far,-3.362994,21.331053,deep,ad,near,-0.832801,0.006682,0.932114,inside in,In,False,21:19:19,374.950012,30-40,1,0-1
71,Youcef Rihane,9,in_play,Forehand,Flat,40.629398,11,2,1,short,deuce,far,-2.930256,12.515554,out,deuce_alley,far,-4.299320,27.012850,0.949235,down the line,Net,False,21:19:21,376.359985,30-40,1,0-1
72,Rudy Quan,1,first_serve,Serve,Slice,80.065468,12,3,1,deep,deuce,far,-1.216550,19.669205,out,deuce,near,1.044041,-0.704540,2.727431,down the T,Out,False,21:19:59,414.570007,0-0,,1-1
73,Rudy Quan,1,second_serve,Serve,Slice,70.076881,12,3,1,short,deuce,far,-0.517171,16.580324,deep,deuce,near,1.094586,-0.172075,2.717412,down the T,In,False,21:20:12,427.220001,0-0,,1-1
74,Youcef Rihane,2,second_return,Backhand,Topspin,41.493507,12,3,1,short,deuce,far,-1.636113,12.338676,out,deuce,far,-1.696906,26.362528,1.026639,inside out,Net,False,21:20:13,428.510010,0-0,,1-1
75,Rudy Quan,1,first_serve,Serve,Slice,81.271683,13,3,1,short,ad,far,2.274055,17.888187,deep,ad,near,-0.805021,-0.250163,2.736556,down the T,In,False,21:20:32,447.640015,15-0,,1-1
76,Youcef Rihane,2,first_return,Backhand,Flat,59.927696,13,3,1,deep,ad,near,-1.742201,1.959931,out,ad,far,4.112262,25.436266,1.125775,cross court,In,False,21:20:33,448.790009,15-0,,1-1
77,Rudy Quan,3,serve_plus_one,Backhand,Topspin,52.050529,13,3,1,deep,ad,far,1.919656,20.253792,out,ad,near,-2.101762,-1.318404,1.040811,cross court,In,False,21:20:35,450.010010,15-0,,1-1
78,Youcef Rihane,4,return_plus_one,Forehand,Topspin,63.407665,13,3,1,deep,ad,near,-2.686007,3.361752,out,ad,far,2.328646,26.136957,1.001597,inside out,In,False,21:20:36,451.480011,15-0,,1-1
79,Rudy Quan,5,in_play,Backhand,Topspin,64.881912,13,3,1,deep,deuce,far,-2.011061,19.444206,out,ad,near,-3.943739,-2.123160,0.919307,down the line,In,False,21:20:37,452.700012,15-0,,1-1
80,Youcef Rihane,6,in_play,Forehand,Topspin,39.408672,13,3,1,short,deuce,far,-1.505266,17.054182,out,deuce,far,-1.919907,25.023176,0.916032,cross court,Net,False,21:20:38,453.929993,15-0,,1-1
81,Rudy Quan,1,first_serve,Serve,Slice,93.338577,14,3,1,short,deuce,far,-0.302544,17.615187,out,deuce,near,1.013995,-0.774998,2.674333,down the T,In,False,21:21:00,475.829987,30-0,,1-1
82,Youcef Rihane,2,first_return,Backhand,Flat,53.129356,14,3,1,short,ad,near,-2.067845,6.181420,out,deuce,far,-1.380000,26.029665,1.231630,inside in,In,False,21:21:01,476.720001,30-0,,1-1
83,Rudy Quan,3,serve_plus_one,Backhand,Flat,69.146057,14,3,1,deep,ad,far,2.011203,18.948143,deep,ad,near,-1.818158,1.734110,0.903125,cross court,In,False,21:21:03,478.100006,30-0,,1-1
84,Youcef Rihane,4,return_plus_one,Backhand,Topspin,46.641445,14,3,1,short,deuce,near,1.092530,9.650946,out,ad,far,3.446729,25.105017,0.875687,down the line,In,False,21:21:04,479.179993,30-0,,1-1
85,Rudy Quan,5,in_play,FH Volley,Flat,20.784662,14,3,1,deep,deuce,far,-3.744650,20.116898,short,deuce,near,1.092530,9.125699,3.042777,cross court,In,False,21:21:04,479.980011,30-0,,1-1
86,Rudy Quan,1,first_serve,Serve,Flat,94.095718,15,3,1,deep,ad,far,3.079996,19.470615,deep,ad,near,-0.747557,-0.132565,2.749042,out wide,Out,False,21:21:30,505.660004,40-0,,1-1
87,Rudy Quan,1,second_serve,Serve,Slice,71.505409,15,3,1,short,ad,far,2.374413,16.659662,deep,ad,near,-0.609282,-0.288511,2.687843,out wide,In,False,21:21:39,514.559998,40-0,,1-1
88,Youcef Rihane,2,second_return,Backhand,Topspin,69.978806,15,3,1,deep,deuce_alley,near,4.730731,2.358247,out,ad,far,3.932586,25.088182,1.297870,down the line,Out,False,21:21:40,515.679993,40-0,,1-1
89,Youcef Rihane,1,first_serve,Serve,Slice,94.177544,16,4,1,short,deuce,far,-0.976586,16.266949,out,deuce,near,0.322922,-0.872968,2.693007,down the T,In,False,21:23:12,607.080017,0-0,,2-1
90,Rudy Quan,2,first_return,Backhand,Topspin,55.094360,16,4,1,deep,ad,near,-0.867309,3.383160,out,deuce,far,-1.543545,26.347683,1.220336,inside in,In,False,21:23:12,607.960022,0-0,,2-1
91,Youcef Rihane,3,serve_plus_one,Forehand,Topspin,65.846603,16,4,1,deep,ad,far,2.037645,19.054485,deep,ad,near,-0.651447,-0.387862,1.060038,inside out,In,False,21:23:14,609.349976,0-0,,2-1
92,Rudy Quan,4,return_plus_one,Backhand,Topspin,55.375134,16,4,1,deep,deuce,near,0.730007,1.308373,out,ad,far,2.756528,26.051432,0.852393,down the line,In,False,21:23:15,610.530029,0-0,,2-1
93,Youcef Rihane,5,in_play,Forehand,Topspin,52.301403,16,4,1,deep,ad,far,3.550163,19.263231,out,deuce,near,0.366247,-1.688886,1.200629,down the line,In,False,21:23:16,611.929993,0-0,,2-1
94,Rudy Quan,6,in_play,Backhand,Topspin,53.162659,16,4,1,out,ad,near,-2.065084,-0.878188,out,ad_alley,far,4.347058,25.644838,1.192100,down the line,Out,False,21:23:18,613.299988,0-0,,2-1
95,Youcef Rihane,1,first_serve,Serve,Slice,80.341354,17,4,1,short,ad,far,2.727561,17.226774,out,ad,near,-1.015735,-0.574519,2.656298,out wide,In,False,21:23:34,629.590027,15-0,,2-1
96,Rudy Quan,2,first_return,Backhand,Topspin,35.775398,17,4,1,short,ad,far,0.586883,12.086058,out,ad_alley,far,4.535880,25.611322,0.798037,down the line,Net,False,21:23:35,630.700012,15-0,,2-1
97,Youcef Rihane,1,first_serve,Serve,Flat,99.835320,18,4,1,short,deuce,far,-2.762587,17.304647,out,deuce,near,0.427502,-0.664076,2.722603,out wide,In,False,21:23:56,651.080017,30-0,,2-1
98,Rudy Quan,2,first_return,Forehand,Flat,54.139496,18,4,1,deep,ad,near,-1.230935,0.957833,out,deuce_alley,far,-4.998730,26.215475,1.035045,down the line,In,False,21:23:56,651.869995,30-0,,2-1
99,Youcef Rihane,3,serve_plus_one,Backhand,Topspin,51.147156,18,4,1,short,ad,far,0.161547,16.994812,out,ad,near,-1.086519,-1.331719,1.005799,cross court,In,False,21:23:58,653.239990,30-0,,2-1
100,Rudy Quan,4,return_plus_one,Forehand,Flat,34.424458,18,4,1,deep,deuce,near,1.565771,4.054794,out,ad,far,0.826373,25.278959,0.725572,inside in,In,False,21:23:59,654.630005,30-0,,2-1
101,Youcef Rihane,5,in_play,Forehand,Topspin,69.427231,18,4,1,deep,deuce,far,-3.123173,19.334927,deep,deuce,near,0.940000,1.030137,1.327796,cross court,In,False,21:24:02,657.039978,30-0,,2-1
102,Rudy Quan,6,in_play,Forehand,Flat,54.802601,18,4,1,short,deuce,near,2.609339,6.149374,out,deuce_alley,far,-5.008751,26.831800,0.833859,down the line,In,False,21:24:03,658.229980,30-0,,2-1
103,Youcef Rihane,1,first_serve,Serve,Slice,93.430367,19,4,1,short,ad,far,3.921988,16.690634,deep,ad,near,-0.612025,0.231339,2.551085,out wide,In,False,21:24:27,682.039978,30-15,,2-1
104,Rudy Quan,2,first_return,Backhand,Topspin,51.029625,19,4,1,short,ad,far,3.369473,17.160728,deep,ad_alley,far,5.298840,24.973366,1.114639,down the line,Net,False,21:24:28,683.119995,30-15,,2-1

### Create shot data csv

In [21]:
# Check existing columns
swing_data.columns

Index(['Player', 'Shot', 'Type', 'Stroke', 'Spin', 'Speed (MPH)', 'Point',
       'Game', 'Set', 'Bounce Depth', 'Bounce Zone', 'Bounce Side',
       'Bounce (x)', 'Bounce (y)', 'Hit Depth', 'Hit Zone', 'Hit Side',
       'Hit (x)', 'Hit (y)', 'Hit (z)', 'Direction', 'Result', 'Favorited',
       'Start Time', 'Video Time', 'pointScore', 'isBreakPoint', 'gameScore'],
      dtype='object')

In [22]:
swing_data.head()

,Player,Shot,Type,Stroke,Spin,Speed (MPH),Point,Game,Set,Bounce Depth,Bounce Zone,Bounce Side,Bounce (x),Bounce (y),Hit Depth,Hit Zone,Hit Side,Hit (x),Hit (y),Hit (z),Direction,Result,Favorited,Start Time,Video Time,pointScore,isBreakPoint,gameScore
0,Rudy Quan,1,first_serve,Serve,Flat,78.818588,1,1,1,short,deuce,near,0.375670,6.704057,out,deuce,far,-1.587323,22.818127,2.682724,down the T,In,False,21:13:17,12.080000,0-0,,0-0
1,Youcef Rihane,2,first_return,Backhand,Topspin,51.792099,1,1,1,deep,deuce,far,-0.948239,19.035049,out,deuce,near,1.339200,-1.593285,0.891651,inside out,In,False,21:13:18,13.040000,0-0,,0-0
2,Rudy Quan,3,serve_plus_one,Forehand,Topspin,58.796837,1,1,1,deep,ad,near,-1.727404,0.906123,deep,deuce,far,-1.565159,24.191404,1.197903,down the line,In,False,21:13:19,14.300000,0-0,,0-0
3,Youcef Rihane,4,return_plus_one,Backhand,Topspin,49.338074,1,1,1,out,ad,far,2.808425,24.438177,out,ad,near,-1.930130,-1.595187,0.957120,cross court,Out,False,21:13:20,15.500000,0-0,,0-0
4,Rudy Quan,5,in_play,Backhand,Flat,56.885868,1,1,1,deep,ad,near,-2.039777,4.713785,deep,ad,far,2.808425,24.145630,0.636929,cross court,In,False,21:13:21,16.959999,0-0,,0-0

In [23]:
# add in all desired column labels, with swingvision labels at end

columm_names = (['pointScore', 'gameScore', 'setScore', 'isPointStart', 
                                         'pointStartTime', 'isPointEnd', 'pointEndTime','pointNumber',
                                         'isBreakPoint','shotInRally','side','serverName',
                                         'serverFarNear','firstServeIn','firstServeZone',
                                         'firstServeXCoord','firstServeYCoord',
                                         'secondServeIn','secondServeZone','secondServeXCoord',
                                         'secondServeYCoord','isAce','shotContactX',
                                         'shotContactY','shotDirection','shotFhBh',
                                         'isSlice','isVolley','isOverhead','isApproach','isDropshot',
                                         'isExcitingPoint','atNetPlayer1','atNetPlayer2','isLob',
                                         'shotLocationX','shotLocationY','isWinner','isErrorWideR', 'isErrorWideL',
                                         'isErrorNet','isErrorLong','clientTeam',
                                         'Date', 'Division', 'Event', 'lineupPosition','matchDetails',
                                         'matchVenue' , 'opponentTeam', 
                                         'player1Name', 'player2Name','player1Hand','player2Hand',
                                        'Round','Surface','Notes'])

shot_data = pd.DataFrame(columns=columm_names)
shot_data

Empty DataFrame
Columns: [pointScore, gameScore, setScore, isPointStart, pointStartTime, isPointEnd, pointEndTime, pointNumber, isBreakPoint, shotInRally, side, serverName, serverFarNear, firstServeIn, firstServeZone, firstServeXCoord, firstServeYCoord, secondServeIn, secondServeZone, secondServeXCoord, secondServeYCoord, isAce, shotContactX, shotContactY, shotDirection, shotFhBh, isSlice, isVolley, isOverhead, isApproach, isDropshot, isExcitingPoint, atNetPlayer1, atNetPlayer2, isLob, shotLocationX, shotLocationY, isWinner, isErrorWideR, isErrorWideL, isErrorNet, isErrorLong, clientTeam, Date, Division, Event, lineupPosition, matchDetails, matchVenue, opponentTeam, player1Name, player2Name, player1Hand, player2Hand, Round, Surface, Notes]
Index: []

### Score Columns

In [24]:
shot_data['pointScore'] = swing_data['pointScore']
shot_data['gameScore'] = swing_data['gameScore']

In [25]:
shot_data.head(50)

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes
0,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,0-15,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,0-15,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,0-15,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,0-15,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,0-15,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,0-15,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,0-30,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,0-30,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,0-30,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,0-30,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,0-30,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,0-40,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,0-40,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,0-40,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,0-40,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,15-40,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,15-40,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,15-40,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,15-40,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,0-0,0-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,0-0,0-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,0-0,0-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,0-0,0-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,15-0,0-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,15-0,0-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,15-0,0-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,15-0,0-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,15-0,0-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,15-0,0-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,15-0,0-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,15-15,0-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,15-15,0-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,15-15,0-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,15-15,0-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,15-15,0-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### isPointStart and isPointEnd columns

In [26]:
def assign_pointstart(x):
    if (x == 'first_serve') | (x == 'second_serve'):
        return 1
    
    return ''

shot_data['isPointStart'] = swing_data['Type'].apply(assign_pointstart)


index_list = []

for i in swing_data['Point'].unique().tolist():
    last_point_index = swing_data[swing_data['Point'] == i].index[-1]
    index_list.append(last_point_index)
    
shot_data.loc[index_list,'isPointEnd'] = 1
shot_data['isPointEnd'] = shot_data['isPointEnd'].fillna('')

### pointStartTime and pointEndTime Columns

In [27]:
# Grab the initial time
match_start_time = re.split(":", swing_data["Start Time"][0])

for i in range(len(swing_data)): # converting into milliseconds
    time = re.split(":", swing_data["Start Time"][i])
    shot_data.loc[i,'pointStartTime'] = ((int(time[0]) - int(match_start_time[0])) *  3600000
                                       + (int(time[1]) - int(match_start_time[1])) *  60000
                                       + (int(time[2]) - int(match_start_time[2])) *  1000)
    
# Assigns last shot time to pointEndTime column
shot_data['pointEndTime'] = np.where(shot_data['isPointEnd'] == 1, shot_data['pointStartTime'], '')

### pointNumber Column

In [28]:
shot_data['pointNumber'] = swing_data['Point']

### isBreakPoint Column

In [29]:
shot_data['isBreakPoint'] = swing_data['isBreakPoint']

### shotInRally column

In [30]:
shot_data.shotInRally = swing_data.Shot

### side column
#### WARNING: outputs 'Center' and we don't have that metric

In [31]:
def side(x):
    if 'deuce' in x:
        return 'Deuce'
    elif 'ad' in x:
        return 'Ad'
    elif 'center_line' in x:
        return 'Center'
    else:
        return ''

shot_data['side'] = swing_data['Hit Zone'].apply(side)

### Players

In [32]:
# ucla roster 23-24 men and womens
ucla_roster_23 = ["Gianluca Ballotta", 
                   "Jeffrey Fradkin", 
                   "Alexander Hoogmartens",
                   "Spencer Johnson",
                   "Stefan Leustian",
                   "Timothy Li",
                   "Govind Nanda",
                   "Jorge Plans Gonzalez",
                   "Giacomo Revelli",
                   "Aadarsh Tripathi",
                   "Emon van Loben Sels",
                   "Azuma Visaya",
                   "Rudy Quan",
                   "Leo Von Bismark",
                   
                   "Tian Fangran",
                   "Bianca Fernandez",
                   "Ahmani Guichard",
                   "Kimmi Hance",
                   "Mia Jovic",
                   "Anne-Christine Lutkemeyer",
                   "Vanessa Ong",
                   "Sasha Vagramov",
                   "Elise Wagle"]

In [33]:
# list of names who are playing in match
players = swing_data["Player"].unique()

# checks which one is UCLA player
is_ucla_player = [any([name in roster_name for roster_name in ucla_roster_23]) for name in players]

In [34]:
# assigns ucla player to player 1, and non ucla to player 2
shot_data.loc[0, "player1Name"] = players[is_ucla_player]
shot_data.loc[0, "player2Name"] = players[np.invert(is_ucla_player)]

### serverName Column

In [35]:
def assign_server_name(stroke, server):
    if stroke != 'Serve':
        return ''
    
    if server.startswith(players[is_ucla_player][0]):
        return 'Player1'
    elif server.startswith(players[np.invert(is_ucla_player)][0]):
        return 'Player2'
    
shot_data['serverName'] = swing_data.apply(lambda x: assign_server_name(x['Stroke'], x['Player']), axis=1)
shot_data['serverName'].replace(['', 'na'], pd.NaT, inplace=True)
shot_data['serverName'] = shot_data['serverName'].ffill()

### serverFarNear Column

In [36]:
shot_data.serverFarNear = np.where((swing_data.Stroke == 'Serve'), np.where(swing_data['Hit Side'] == 'far', 'Far', 'Near'), '')
shot_data['serverFarNear'].replace(['', 'na'], pd.NaT, inplace=True)
shot_data['serverFarNear'] = shot_data['serverFarNear'].ffill()

### firstServeIn and secondServeIn Columns

In [37]:
shot_data.firstServeIn = np.where((swing_data.Type == 'first_serve'),np.where((shot_data.isPointStart == 1) & (swing_data['Result'] == 'In'), 1, 0), np.nan)
shot_data.secondServeIn =np.where((swing_data.Type == 'second_serve') & (shot_data.isPointStart == 1), np.where(swing_data['Result'] == 'In', 1,0), np.nan)

### SwingVision Coord Transformation
court coordinates
swing vision - meters, near side center marks (0,0)
singles court x [-4.1148, 4.1148], y [0, 23.7744]
doubles court x [-5.485, 5.485]

our coordinates - center of net (0,0)
singles court x [-157.5, 157.5], y [-455, 455]

shot_x = (157.5/4.1148) * swing_x
shot_y = (455/11.8872) * swing_y + 455
ratio = 38.2764654418

### firstServeXCoord, firstYServeYCoord, secondServeXCoord, and secondServeyCoord Columns

In [38]:
def first_serve_x_coordinates(stroke, x):
    if stroke == 'first_serve':
        return x * 38.2764654418
    else:
        return np.nan

def first_serve_y_coordinates(stroke, y):
    if stroke == 'first_serve':
        return (y - 11.8872) * 38.2764654418
    else:
        return np.nan
    
shot_data['firstServeXCoord'] = swing_data.apply(lambda row: first_serve_x_coordinates(row['Type'], row['Bounce (x)']), axis=1)
shot_data['firstServeYCoord'] = swing_data.apply(lambda row: first_serve_y_coordinates(row['Type'], row['Bounce (y)']), axis=1)


def second_serve_x_coordinates(stroke, x):
    if stroke == 'second_serve':
        return x * 38.2764654418
    else:
        return np.nan

def second_serve_y_coordinates(stroke, y):
    if stroke == 'second_serve':
        return (y - 11.8872) * 38.2764654418
    else:
        return np.nan
    
shot_data['secondServeXCoord'] = swing_data.apply(lambda row: second_serve_x_coordinates(row['Type'], row['Bounce (x)']), axis=1)
shot_data['secondServeYCoord'] = swing_data.apply(lambda row: second_serve_y_coordinates(row['Type'], row['Bounce (y)']), axis=1)

### firstServeZone and secondServeZone Columns
- serving zones: T, Body, Wide
- Wide: x in [-inf, -105] u [105, inf]
- Body: x in [-105, -52.5] u [52.5, 105]
- T: x in [-52.5, 52.5]

In [39]:
def label_zone(x_coord):
    if x_coord != '':
        x_coord = float(x_coord)
        if (x_coord < -105) | (x_coord > 105):
            return 'Wide'
        elif (-105 <= x_coord <= -52.5) | (52.5 <= x_coord <= 105):
            return 'Body'
        elif -52.5 < x_coord < 52.5:
            return 'T'
    return ''

# convert x coord to serve zone
shot_data.firstServeZone = shot_data.firstServeXCoord.apply(label_zone)
shot_data.secondServeZone = shot_data.secondServeXCoord.apply(label_zone)

In [40]:
shot_data.head()

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes
0,0-0,0-0,NaN,1,0,,,1,,1,Deuce,Player1,Far,1.0,T,14.37932,-198.392394,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rudy Quan,Youcef Rihane,NaN,NaN,NaN,NaN,NaN
1,0-0,0-0,NaN,,1000,,,1,,2,Deuce,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0-0,0-0,NaN,,2000,,,1,,3,Deuce,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-0,0-0,NaN,,3000,,,1,,4,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0-0,0-0,NaN,,4000,,,1,,5,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### isAce Column
- WARNING: Not accurate
- FIX: counts double faults as aces

In [41]:
shot_data['isAce'] = np.where((swing_data.Stroke == 'Serve') & 
                              (shot_data.isPointEnd == 1) & 
                              (shot_data.secondServeIn != 0), 1, np.nan)

In [42]:
shot_data[460:600]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes
460,0-0,2-1,NaN,,2943000,,,71,,3,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
461,0-0,2-1,NaN,,2944000,,,71,,4,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
462,0-0,2-1,NaN,,2945000,,,71,,5,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
463,0-0,2-1,NaN,,2946000,,,71,,6,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
464,0-0,2-1,NaN,,2947000,1,2947000,71,,7,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
465,15-0,2-1,NaN,1,2969000,,,72,,1,Ad,Player2,Far,1.0,Body,-70.052707,-234.717678,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
466,15-0,2-1,NaN,,2970000,,,72,,2,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
467,15-0,2-1,NaN,,2971000,1,2971000,72,,3,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
468,15-15,2-1,NaN,1,2990000,,,73,,1,Deuce,Player2,Far,1.0,T,13.697539,-240.692481,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469,15-15,2-1,NaN,1,3003000,,,73,,1,Deuce,Player2,Far,NaN,,NaN,NaN,1.0,T,46.524738,-220.587156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
470,15-15,2-1,NaN,,3004000,,,73,,2,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
471,15-15,2-1,NaN,,3005000,,,73,,3,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
472,15-15,2-1,NaN,,3006000,,,73,,4,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
473,15-15,2-1,NaN,,3008000,,,73,,5,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
474,15-15,2-1,NaN,,3009000,,,73,,6,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
475,15-15,2-1,NaN,,3010000,1,3010000,73,,7,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
476,15-30,2-1,NaN,1,3036000,,,74,,1,Ad,Player2,Far,1.0,Wide,-144.012292,-210.614146,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
477,15-30,2-1,NaN,,3037000,1,3037000,74,,2,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
478,30-30,2-1,NaN,1,3061000,,,75,,1,Deuce,Player2,Far,1.0,T,20.844368,-185.122096,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
479,30-30,2-1,NaN,,3062000,,,75,,2,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
480,30-30,2-1,NaN,,3063000,,,75,,3,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
481,30-30,2-1,NaN,,3064000,,,75,,4,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
482,30-30,2-1,NaN,,3065000,,,75,,5,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
483,30-30,2-1,NaN,,3066000,,,75,,6,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
484,30-30,2-1,NaN,,3067000,,,75,,7,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
485,30-30,2-1,NaN,,3068000,1,3068000,75,,8,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
486,30-40,2-1,NaN,1,3092000,1,3092000,76,1,1,Ad,Player2,Far,1.0,T,-2.191251,-231.307092,NaN,,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487,40-40,2-1,NaN,1,3108000,,,77,1,1,Deuce,Player2,Far,1.0,T,17.518602,-241.474584,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488,40-40,2-1,NaN,,3109000,,,77,1,2,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
489,40-40,2-1,NaN,,3110000,,,77,1,3,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
490,40-40,2-1,NaN,,3112000,,,77,1,4,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
491,40-40,2-1,NaN,,3113000,1,3113000,77,1,5,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
492,0-0,3-1,NaN,1,3151000,,,78,,1,Deuce,Player1,Near,0.0,Body,-54.250344,246.948999,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
493,0-0,3-1,NaN,,3152000,,,78,,2,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
494,0-0,3-1,NaN,,3153000,,,78,,3,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
495,0-0,3-1,NaN,,3155000,,,78,,4,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,0-0,3-1,NaN,,3156000,1,3156000,78,,5,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
497,0-15,3-1,NaN,1,3177000,,,79,,1,Ad,Player1,Near,1.0,Wide,118.185439,243.053565,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
498,0-15,3-1,NaN,,3178000,,,79,,2,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499,0-15,3-1,NaN,,3180000,,,79,,3,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
500,0-15,3-1,NaN,,3181000,,,79,,4,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
501,0-15,3-1,NaN,,3182000,,,79,,5,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
502,0-15,3-1,NaN,,3184000,,,79,,6,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
503,0-15,3-1,NaN,,3185000,,,79,,7,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
504,0-15,3-1,NaN,,3186000,,,79,,8,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
505,0-15,3-1,NaN,,3188000,,,79,,9,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506,0-15,3-1,NaN,,3189000,,,79,,10,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
507,0-15,3-1,NaN,,3191000,,,79,,11,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
508,0-15,3-1,NaN,,3192000,,,79,,12,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
509,0-15,3-1,NaN,,3193000,,,79,,13,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
510,0-15,3-1,NaN,,3194000,,,79,,14,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
511,0-15,3-1,NaN,,3196000,1,3196000,79,,15,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
512,15-15,3-1,NaN,1,3225000,,,80,,1,Deuce,Player1,Near,1.0,Wide,-124.623961,184.744116,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
513,15-15,3-1,NaN,,3226000,,,80,,2,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
514,15-15,3-1,NaN,,3228000,,,80,,3,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
515,15-15,3-1,NaN,,3229000,,,80,,4,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
516,15-15,3-1,NaN,,3230000,,,80,,5,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
517,15-15,3-1,NaN,,3231000,1,3231000,80,,6,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
518,30-15,3-1,NaN,1,3261000,,,81,,1,Ad,Player1,Near,0.0,Body,57.829003,-28.876378,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
519,30-15,3-1,NaN,1,3271000,,,81,,1,Ad,Player1,Near,NaN,,NaN,NaN,1.0,Body,89.990573,219.551892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
520,30-15,3-1,NaN,,3272000,,,81,,2,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
521,30-15,3-1,NaN,,3273000,,,81,,3,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
522,30-15,3-1,NaN,,3274000,,,81,,4,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
523,30-15,3-1,NaN,,3276000,,,81,,5,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
524,30-15,3-1,NaN,,3277000,,,81,,6,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
525,30-15,3-1,NaN,,3278000,,,81,,7,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
526,30-15,3-1,NaN,,3279000,1,3279000,81,,8,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
527,40-15,3-1,NaN,1,3310000,,,82,,1,Deuce,Player1,Near,1.0,T,-28.319876,244.696161,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
528,40-15,3-1,NaN,,3311000,,,82,,2,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
529,40-15,3-1,NaN,,3312000,,,82,,3,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
530,40-15,3-1,NaN,,3314000,,,82,,4,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
531,40-15,3-1,NaN,,3315000,1,3315000,82,,5,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
532,40-30,3-1,NaN,1,3347000,,,83,,1,Ad,Player1,Near,1.0,Wide,107.553576,232.348824,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
533,40-30,3-1,NaN,,3348000,1,3348000,83,,2,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
534,0-0,4-1,NaN,1,3451000,,,84,,1,Deuce,Player2,Near,1.0,Wide,-142.926465,239.164676,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
535,0-0,4-1,NaN,,3452000,,,84,,2,Deuce,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
536,0-0,4-1,NaN,,3453000,,,84,,3,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
537,0-0,4-1,NaN,,3454000,,,84,,4,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
538,0-0,4-1,NaN,,3456000,,,84,,5,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
539,0-0,4-1,NaN,,3457000,1,3457000,84,,6,Deuce,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
540,15-0,4-1,NaN,1,3478000,,,85,,1,Ad,Player2,Near,0.0,Wide,176.502772,275.481540,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
541,15-0,4-1,NaN,1,3486000,,,85,,1,Ad,Player2,Near,1.0,Body,102.363326,149.580140,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
542,15-0,4-1,NaN,1,3516000,,,85,,1,Ad,Player2,Near,0.0,T,-5.081890,161.407644,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
543,15-0,4-1,NaN,1,3541000,,,85,,1,Ad,Player2,Near,0.0,Wide,168.738927,243.030217,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
544,15-0,4-1,NaN,1,3550000,,,85,,1,Ad,Player2,Near,NaN,,NaN,NaN,1.0,Body,103.763670,158.562363,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
shot_data[shot_data['isAce'] == 1]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes
486,30-40,2-1,NaN,1,3092000,1,3092000,76,1,1,Ad,Player2,Far,1.0,T,-2.191251,-231.307092,NaN,,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### shotContactX and shotContactY Columns

In [44]:
# Functions to transform the swingvision coordinates
def transf_x_coord_sv_to_shot(sv_col) :
    return sv_col * 38.2764654418
def transf_y_coord_sv_to_shot(sv_col) :
    return (sv_col - 11.8872) * 38.2764654418

# want to convert swingvision coordinates into our own
shot_data['shotContactX'] = transf_x_coord_sv_to_shot(swing_data['Hit (x)'])
shot_data['shotContactY'] = transf_y_coord_sv_to_shot(swing_data['Hit (y)'])

### shotDirection column

In [45]:
# down the line --> switches btwn deuce and ad
# crosscourt --> remains on same side
shot_data['shotDirection'] = np.where((shot_data.shotContactX * shot_data.shotLocationX > 0) & (shot_data.shotInRally != 1), "Down the Line", 
    np.where(shot_data.shotInRally != 1, 'Crosscourt', ''))

### shotFhBh Column

In [46]:
def classify_shot(stroke):
    if stroke == 'FH Volley':
        return 'Forehand'
    elif stroke == 'BH Volley':
        return 'Backhand'
    elif stroke == 'Forehand':
        return 'Forehand'
    elif stroke == 'Backhand':
        return 'Backhand'
    elif stroke == 'Overhead':
        return 'Forehand'
    else:
        return ''

# Applying the function to the DataFrame
shot_data['shotFhBh'] = swing_data['Stroke'].apply(classify_shot)

### isSlice, isTopspin, isFlat, isKick Columns

In [47]:
shot_data['isSlice'] = swing_data['Spin'].apply(lambda x: '1' if x == 'Slice' else '')
shot_data['isTopspin'] = swing_data['Spin'].apply(lambda x: '1' if x == 'Topspin' else '') # added these metrics
shot_data['isFlat'] = swing_data['Spin'].apply(lambda x: '1' if x == 'Flat' else '') # added these metrics
shot_data['isKick'] = swing_data['Spin'].apply(lambda x: '1' if x == 'Kick' else '') # added these metrics

### isVolley Column
- Volleys are inaccurate

In [48]:
shot_data['isVolley'] = swing_data['Stroke'].apply(lambda x: 1 if x in ['FH Volley', 'BH Volley'] else '') # need to classify shotFhBh when doing isVolley

In [49]:
shot_data[shot_data['isVolley'] == 1]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick
85,30-0,1-1,NaN,,467000,1,467000,14,,5,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,41.818187,-105.700498,Crosscourt,Forehand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
168,40-15,3-2,NaN,,1116000,1,1116000,30,,5,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-60.708541,326.462423,Crosscourt,Forehand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
216,0-0,4-3,NaN,,1436000,1,1436000,37,,6,Deuce,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-97.921265,331.683754,Crosscourt,Backhand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
240,40-15,4-3,NaN,,1554000,,,41,,5,Deuce,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,31.284848,-117.005643,Crosscourt,Forehand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
299,15-15,5-4,NaN,,1890000,,,49,,10,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-12.982918,-42.976892,Crosscourt,Forehand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
320,30-40,5-4,NaN,,2001000,,,52,1,7,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-1.237631,-61.203800,Crosscourt,Forehand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
323,30-40,5-4,NaN,,2004000,,,52,1,10,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,21.610548,393.996921,Crosscourt,Backhand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
337,15-15,0-0,NaN,,2189000,1,2189000,55,,5,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-19.854921,-180.051651,Crosscourt,Backhand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
380,0-30,0-1,NaN,,2447000,,,61,,10,Deuce,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,83.669062,-182.624098,Crosscourt,Forehand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
409,0-0,1-1,NaN,,2608000,,,65,,12,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-106.438698,-270.168039,Crosscourt,Backhand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
464,0-0,2-1,NaN,,2947000,1,2947000,71,,7,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-64.835739,285.579331,Crosscourt,Forehand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
483,30-30,2-1,NaN,,3066000,,,75,,6,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-113.517049,-315.436581,Crosscourt,Backhand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
485,30-30,2-1,NaN,,3068000,1,3068000,75,,8,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-135.455397,277.263960,Crosscourt,Forehand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
552,30-0,4-1,NaN,,3586000,,,86,,5,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-67.807524,-148.845883,Crosscourt,Backhand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
603,0-0,5-2,NaN,,3903000,1,3903000,93,,5,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-115.220850,318.929385,Crosscourt,Forehand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,

### isOverhead Column
- Overheads are inaccurate

In [50]:
shot_data['isOverhead'] = swing_data['Stroke'].apply(lambda x: 1 if x == 'Overhead' else '')

In [51]:
shot_data[shot_data['isOverhead'] == 1]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick
137,15-15,2-2,NaN,,817000,1,817000,23,,5,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,63.130446,225.777444,Crosscourt,Forehand,,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
147,40-15,2-2,NaN,,893000,1,893000,25,,7,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,9.682376,279.528013,Crosscourt,Forehand,,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
238,40-15,4-3,NaN,,1552000,,,41,,3,Deuce,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,91.642049,-276.517378,Crosscourt,Forehand,,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
322,30-40,5-4,NaN,,2003000,,,52,1,9,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,11.070243,-121.225509,Crosscourt,Forehand,,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
452,30-30,1-1,NaN,,2811000,1,2811000,69,,5,Deuce,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-44.067809,305.622036,Crosscourt,Forehand,,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
531,40-15,3-1,NaN,,3315000,1,3315000,82,,5,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,21.518531,-181.177018,Crosscourt,Forehand,,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,

### isApproach Column

### isDropshot Column

### isExcitingPoint

### atNetPlayer1 and atNetPlayer2 Columns

### isLob Column

### shotLocationX and shotLocationY Columns

In [52]:
# Functions to transform the swingvision coordinates
def transf_x_loc(stroke, sv_col):
    if stroke != 'first_serve' and stroke != 'second_serve':
        return sv_col * 38.2764654418
    return np.nan
    
def transf_y_loc(stroke, sv_col):
    if stroke != 'first_serve' and stroke != 'second_serve':
        return (sv_col - 11.8872) * 38.2764654418
    return np.nan

# want to convert swingvision coordinates into our own
shot_data['shotLocationX'] = swing_data.apply(lambda x: transf_x_loc(x['Type'], x['Bounce (x)']), axis=1)
shot_data['shotLocationY'] = swing_data.apply(lambda x: transf_y_loc(x['Type'], x['Bounce (y)']), axis=1)

### isWinner Column

In [53]:
shot_data.isWinner = np.where((shot_data.isPointEnd == 1) & (shot_data.secondServeIn != '0') &
                              (swing_data.Result == 'In'), 1, np.nan)

In [54]:
shot_data[shot_data['isWinner'] == 1]
# shot_data[330:345]
shot_data[shot_data['pointNumber'] == 10]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick
60,15-40,0-1,NaN,1,324000,,,10,1,1,Deuce,Player2,Far,1.0,Body,55.025022,-169.492055,NaN,,NaN,NaN,NaN,-18.862259,450.213260,,,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
61,15-40,0-1,NaN,,325000,1,325000,10,1,2,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,77.816514,-490.483815,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,32.361144,-20.408552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,

### isErrorWideR

In [55]:
def wide_right_function(side, x, y, end):
    if (side == 'far' and x < -157.5 and y > -405 and y < 0 and end == 1) or (side == 'near' and x > 157.5 and y < 405 and y > 0 and end == 1):
        return 1
    return np.nan

# Assign 'isErrorWideR' using values from both 'swing_data' and 'shot_data'
shot_data['isErrorWideR'] = shot_data.apply(lambda x: wide_right_function(swing_data.loc[x.name, 'Hit Side'], 
                                                                x['shotLocationX'], x['shotLocationY'], x['isPointEnd']), axis=1)

### isErrorWideL

In [56]:
def wide_left_function(side, x, y, end):
    if (side == 'far' and x > 157.5 and y > -405 and y < 0 and end == 1) or (side == 'near' and x < -157.5 and y < 405 and y > 0 and end == 1):
        return 1
    return np.nan

# Assign 'isErrorWideR' using values from both 'swing_data' and 'shot_data'
shot_data['isErrorWideL'] = shot_data.apply(lambda x: wide_left_function(swing_data.loc[x.name, 'Hit Side'], 
                                                                x['shotLocationX'], x['shotLocationY'], x['isPointEnd']), axis=1)

### isErrorNet Column

In [57]:
shot_data.isErrorNet = np.where((swing_data.Result == 'Net'), 1, np.nan)

### isErrorLong Column

In [58]:
shot_data['isErrorLong'] = np.where((swing_data['Result'] == 'Out') & (shot_data['shotLocationY'].abs() > 455), 1, np.nan)

In [59]:
shot_data[shot_data['isErrorLong'] == 1]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick
3,0-0,0-0,NaN,,3000,,,1,,4,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-73.878554,-516.058120,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,107.496582,480.407037,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
59,15-30,0-1,NaN,,298000,1,298000,9,,7,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,57.685887,514.961767,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,135.932437,-511.711445,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
94,0-0,2-1,NaN,,601000,1,601000,16,,6,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,166.390015,526.593755,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-79.044116,-488.613933,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
108,40-15,2-1,NaN,,693000,1,693000,20,,4,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,122.223912,511.705244,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,113.376537,-516.193274,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
140,30-15,2-2,NaN,,864000,1,864000,24,,2,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-146.471632,-486.725448,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-106.390469,455.887708,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
171,0-0,3-3,NaN,,1155000,,,31,,2,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-89.448272,492.106507,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-79.583470,-496.869477,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
227,0-15,4-3,NaN,,1472000,1,1472000,38,,10,Deuce,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-204.747512,565.763019,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-66.299852,-478.467760,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
300,15-15,5-4,NaN,,1892000,1,1892000,49,,11,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-125.516109,490.621916,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,10.122671,-491.770287,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
326,0-0,0-0,NaN,,2131000,,,53,,2,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-98.311035,553.200569,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,77.875191,-475.553505,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
332,15-0,0-0,NaN,,2161000,1,2161000,54,,3,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-56.489939,-505.969707,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,66.115972,508.054932,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
347,15-40,0-0,NaN,,2238000,1,2238000,57,1,5,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-80.731955,-495.082502,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-127.007743,460.095669,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
384,0-40,0-1,NaN,,2482000,,,62,1,3,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-25.657021,-486.306168,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-93.471703,457.004653,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
439,15-15,1-1,NaN,,2732000,,,67,,3,Deuce,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-144.467897,436.091196,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-21.282825,-510.493755,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
526,30-15,3-1,NaN,,3279000,1,3279000,81,,8,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,136.175339,472.289288,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-113.346911,-498.941344,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
587,30-0,4-2,NaN,,3747000,1,3747000,91,,6,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-136.640398,-535.501033,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,131.902652,547.043416,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,

In [60]:
shot_data[160:175]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick
160,30-0,3-2,NaN,,1050000,1,1050000,28,,7,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,38.522047,522.342159,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-45.526181,12.591847,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
161,30-15,3-2,NaN,1,1075000,,,29,,1,Ad,Player2,Far,0.0,T,-41.975312,-268.816727,NaN,,NaN,NaN,NaN,34.480818,449.593679,,,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
162,30-15,3-2,NaN,1,1085000,,,29,,1,Ad,Player2,Far,NaN,,NaN,NaN,1.0,Wide,-124.436483,-183.382622,NaN,16.331841,434.450935,,,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
163,30-15,3-2,NaN,,1086000,1,1086000,29,,2,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-192.853981,-453.612823,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-44.787943,-23.909126,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
164,40-15,3-2,NaN,1,1112000,,,30,,1,Deuce,Player2,Far,1.0,Wide,134.468017,-238.282672,NaN,,NaN,NaN,NaN,-39.666628,466.585138,,,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
165,40-15,3-2,NaN,,1112000,,,30,,2,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,184.219078,-486.791475,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,23.280206,299.686313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
166,40-15,3-2,NaN,,1114000,,,30,,3,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-10.896123,513.678319,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-119.287686,-270.727105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
167,40-15,3-2,NaN,,1115000,,,30,,4,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-175.944625,-530.911379,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-60.708541,280.194291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
168,40-15,3-2,NaN,,1116000,1,1116000,30,,5,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-60.708541,326.462423,Crosscourt,Forehand,,1,,NaN,NaN,NaN,NaN,NaN,NaN,115.810537,-337.796391,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
169,0-0,3-3,NaN,1,1145000,,,31,,1,Deuce,Player1,Near,0.0,T,-36.715054,277.049229,NaN,,NaN,NaN,NaN,41.412073,-460.588900,,,1,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,
170,0-0,3-3,NaN,1,1154000,,,31,,1,Deuce,Player1,Near,NaN,,NaN,NaN,1.0,T,-44.305200,178.460728,NaN,45.958284,-462.673972,,,1,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,
171,0-0,3-3,NaN,,1155000,,,31,,2,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-89.448272,492.106507,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-79.583470,-496.869477,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
172,0-0,3-3,NaN,,1156000,,,31,,3,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-79.583470,-516.974076,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,80.626198,209.047184,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
173,0-0,3-3,NaN,,1158000,1,1158000,31,,4,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,63.283590,220.639326,Crosscourt,Backhand,1,,,NaN,NaN,NaN,NaN,NaN,NaN,-0.975514,-294.596730,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,
174,15-0,3-3,NaN,1,1182000,,,32,,1,Ad,Player1,Near,0.0,Wide,130.840174,246.651706,NaN,,NaN,NaN,NaN,-19.402800,-478.918313,,,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,

### Group First Serve and Second Serve Columns

In [63]:
shot_data[shot_data['pointNumber'] == 9]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick
52,15-30,0-1,NaN,1,277000,,,9,,1,Ad,Player2,Far,0.0,Body,-55.493564,1.242799,NaN,,NaN,NaN,NaN,22.501203,495.838309,,,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
53,15-30,0-1,NaN,1,290000,,,9,,1,Ad,Player2,Far,NaN,,NaN,NaN,1.0,Wide,-111.856004,-151.853418,NaN,13.708142,437.246572,,,1,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,
54,15-30,0-1,NaN,,291000,,,9,,2,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-197.341743,-469.557918,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,45.830823,371.611045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
55,15-30,0-1,NaN,,292000,,,9,,3,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,63.176378,529.499284,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,93.813052,-339.371621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
56,15-30,0-1,NaN,,294000,,,9,,4,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,86.370194,-532.638337,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-49.296451,277.525580,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
57,15-30,0-1,NaN,,295000,,,9,,5,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-96.665797,524.920308,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-131.385575,-398.101537,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
58,15-30,0-1,NaN,,296000,,,9,,6,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-137.191082,-534.383016,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,62.978144,358.394029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
59,15-30,0-1,NaN,,298000,1,298000,9,,7,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,57.685887,514.961767,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,135.932437,-511.711445,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,

In [64]:
test_df = shot_data[shot_data['pointNumber'] == 9]
test_df

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick
52,15-30,0-1,NaN,1,277000,,,9,,1,Ad,Player2,Far,0.0,Body,-55.493564,1.242799,NaN,,NaN,NaN,NaN,22.501203,495.838309,,,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
53,15-30,0-1,NaN,1,290000,,,9,,1,Ad,Player2,Far,NaN,,NaN,NaN,1.0,Wide,-111.856004,-151.853418,NaN,13.708142,437.246572,,,1,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,
54,15-30,0-1,NaN,,291000,,,9,,2,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-197.341743,-469.557918,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,45.830823,371.611045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
55,15-30,0-1,NaN,,292000,,,9,,3,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,63.176378,529.499284,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,93.813052,-339.371621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
56,15-30,0-1,NaN,,294000,,,9,,4,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,86.370194,-532.638337,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-49.296451,277.525580,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
57,15-30,0-1,NaN,,295000,,,9,,5,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-96.665797,524.920308,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-131.385575,-398.101537,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
58,15-30,0-1,NaN,,296000,,,9,,6,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-137.191082,-534.383016,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,62.978144,358.394029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
59,15-30,0-1,NaN,,298000,1,298000,9,,7,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,57.685887,514.961767,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,135.932437,-511.711445,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,

In [95]:
# All columns
default_cols = ['pointScore', 'gameScore', 'setScore', 'isPointStart', 'pointStartTime',
       'isPointEnd', 'pointEndTime', 'pointNumber', 'isBreakPoint',
       'shotInRally', 'side', 'serverName', 'serverFarNear', 'firstServeIn',
       'firstServeZone', 'firstServeXCoord', 'firstServeYCoord',
       'secondServeIn', 'secondServeZone', 'secondServeXCoord',
       'secondServeYCoord', 'isAce', 'shotContactX', 'shotContactY',
       'shotDirection', 'shotFhBh', 'isSlice', 'isVolley', 'isOverhead',
       'isApproach', 'isDropshot', 'isExcitingPoint', 'atNetPlayer1',
       'atNetPlayer2', 'isLob', 'shotLocationX', 'shotLocationY', 'isWinner',
       'isErrorWideR', 'isErrorWideL', 'isErrorNet', 'isErrorLong',
       'clientTeam', 'Date', 'Division', 'Event', 'lineupPosition',
       'matchDetails', 'matchVenue', 'opponentTeam', 'player1Name',
       'player2Name', 'player1Hand', 'player2Hand', 'Round', 'Surface',
       'Notes', 'isTopspin', 'isFlat', 'isKick']

# Assign all columns to have value be taken from the first serve row
agg_dict = {col: 'first' for col in default_cols}

# Reassign select columns to have value be taken form the second serve row
agg_dict.update({'isPointEnd': 'last', 
                 'pointEndTime': 'last', 
                 'secondServeIn' : 'last',
                 'secondServeZone' : 'last',
                 'secondServeXCoord' : 'last', 
                 'secondServeYCoord' : 'last',
                 'isAce' : 'last', 
                 'shotContactX' : 'last', 
                 'shotContactY' : 'last',
                 'isWinner' : 'last',
                 'isErrorWideR' : 'last',
                 'isErrorWideL' : 'last', 
                 'isErrorNet' : 'last',
                 'isErrorLong' : 'last'
                })

# Group by isPointStart and pointNumber
grouped_df = shot_data.groupby(['shotInRally', 'pointNumber'], as_index=False).agg(agg_dict)
shot_data = grouped_df.sort_values(by=['pointNumber', 'shotInRally'], ascending=[True, True]).reset_index(drop = True)

In [96]:
shot_data.head()

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick
0,0-0,0-0,None,1,0,,,1,,1,Deuce,Player1,Far,1.0,T,14.37932,-198.392394,NaN,,NaN,NaN,NaN,-60.757114,418.397250,,,,,,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,Rudy Quan,Youcef Rihane,None,None,None,None,None,,1,
1,0-0,0-0,None,,1000,,,1,,2,Deuce,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,51.259843,-515.985318,Crosscourt,Backhand,,,,None,None,None,None,None,None,-36.295237,273.594395,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1,,
2,0-0,0-0,None,,2000,,,1,,3,Deuce,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-59.908754,470.961439,Crosscourt,Forehand,,,,None,None,None,None,None,None,-66.118920,-420.316814,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1,,
3,0-0,0-0,None,,3000,,,1,,4,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-73.878554,-516.058120,Crosscourt,Backhand,,,,None,None,None,None,None,None,107.496582,480.407037,NaN,NaN,NaN,NaN,1.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1,,
4,0-0,0-0,None,,4000,,,1,,5,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,107.496582,469.209372,Crosscourt,Backhand,,,,None,None,None,None,None,None,-78.075454,-274.572971,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,,1,

### Save as CSV

In [ ]:
# if want to drop swingvision coords, drops all columns after 'Notes'
# shot_data = shot_data.loc[:, :'Notes']

shot_data.to_csv('swing_vision.csv', index=False)

### Serving Columns
#### * need to revise code for determining serves in/out
- if want to hardcode it:
- far deuce serve: x [0, 157.5], y [-245, 0]
- near deuce serve: x [-157.5, 0], y [0, 245]
- far ad serve: x [-157.5, 0], y [-245, 0]
- near ad serve: x [0, 157.5], y [0, 245]

### Points

In [ ]:
# ad scoring?

ad_scoring = False

In [ ]:
# want to record the score every time a point ends
# points: server - returner
# games: ucla (player1) - opp
# sets: ucla (player1) - opp
points = np.zeros(2)
games = np.zeros(2)
sets = np.zeros(2)
pt_values = [0, 15, 30, 40]



shot_data.loc[0,"pointScore"] = f"{pt_values[int(points[0])]} - {pt_values[int(points[1])]}"
shot_data.loc[0,"gameScore"] = f"{games[0]} - {games[1]}"
shot_data.loc[0,"setScore"] = f"{sets[0]} - {sets[1]}"

shot_data["isBreakPoint"] = ''

error_cols = [x for x in shot_data.columns if "isError" in x]

for i in range(0, len(shot_data.pointScore) - 1):
    if shot_data.loc[i+1, "isPointStart"] == 1: # means we gotta update pts
        # determine point score by checking last shot
        if shot_data.loc[i, "isWinner"] == "1":
            # check if player 1 or 2 won pt
            pt_winner_player_num = (np.where(shot_data.loc[i, "Player"] == shot_data.loc[0,"player1Name"], '1', '2'))
        elif shot_data.loc[i, 'secondServeIn'] == "0": # double fault
            pt_winner_player_num = (np.where(shot_data.loc[i, "Player"] == shot_data.loc[0,"player1Name"], '2', '1'))
        elif any(shot_data.loc[i,error_cols] == "1"):
            # winner is the player who did NOT hit that shot
            pt_winner_player_num = (np.where(shot_data.loc[i, "Player"] == shot_data.loc[0,"player1Name"], '2', '1'))
        else:
            print("no pt recorded at row ", i)

        if shot_data.loc[i, "serverName"] is not None:
            didServerWinPt = shot_data.loc[i, "serverName"][-1] == pt_winner_player_num
        else:
            print(f"Server name is None at row {i}. Skipping this point.")
            continue  # Skip this point if server name is None
        
        if didServerWinPt:
            points[0] += 1
        else:
            points[1] += 1


        if ad_scoring: # checks if need to win by 2
            if any(points > 3) and abs(points[0] - points[1]) >= 2:
                game_winner = np.argmax(points)  # Find who won the game
                games[game_winner] += 1
                points = np.zeros(2)  # Reset point values
            if any(games > 5) and abs(games[0] - games[1]) >= 2:
                set_winner = np.argmax(games)  # Find who won the set
                sets[set_winner] += 1
                games = np.zeros(2)  # Reset game values   
        else:
            if points[1] == 3: # if the returner has 40 pts and can win the game
                shot_data.loc[i + 1, 'isBreakPoint'] = '1'
            if any(points > 3):
                game_winner = np.argmax(points)  # Find who won the game
                games[game_winner] += 1
                points = np.zeros(2)  # Reset point values
            if any(games > 5):
                set_winner = np.argmax(games)  # Find who won the set
                sets[set_winner] += 1
                games = np.zeros(2)  # Reset game values   

    # Update the scores in the shot_data DataFrame
    shot_data.loc[i+1,"pointScore"] = f"{pt_values[int(points[0])]} - {pt_values[int(points[1])]}"
    shot_data.loc[i+1,"gameScore"] = f"{int(games[0])} - {int(games[1])}"
    shot_data.loc[i+1,"setScore"] = f"{int(sets[0])} - {int(sets[1])}"


# Additional comments for further updates:
# - Tiebreak scenarios are not yet handled and need to be accounted for in future versions.